Repository OCA/maintenance, pull requests merged in 2020-09, with the labels that each got.

#95 [12.0][ADD] Add Maintenance Request Repair
  maintenance_request_repair/README.rst
  maintenance_request_repair/__init__.py
  maintenance_request_repair/__manifest__.py
  maintenance_request_repair/i18n/maintenance_request_repair.pot
  maintenance_request_repair/i18n/pt_BR.po
  maintenance_request_repair/models/__init__.py
  maintenance_request_repair/models/maintenance_request.py
  maintenance_request_repair/models/repair_order.py
  maintenance_request_repair/readme/CONTRIBUTORS.rst
  maintenance_request_repair/readme/DESCRIPTION.rst
  maintenance_request_repair/readme/USAGE.rst
  maintenance_request_repair/static/description/icon.png
  maintenance_request_repair/static/description/index.html
  maintenance_request_repair/views/maintenance_request.xml
  maintenance_request_repair/views/repair_order.xml
Labels: bot is merging ⏳, needs review

#105 [12.0][FIX] maintenance_timesheet: use button placeholder in request form
  maintenance_timesheet/views/maintenance_request_views.xml
Labels: approved, bot is merging ⏳

#106 [IMP] maintenance_equipment_tags: Improve readme
  maintenance_equipment_tags/README.rst
  maintenance_equipment_tags/readme/DESCRIPTION.rst
  maintenance_equipment_tags/static/description/index.html
Labels: approved, bot is merging ⏳

#104 [12.0][ADD] maintenance_stock
  maintenance_stock/README.rst
  maintenance_stock/__init__.py
  maintenance_stock/__manifest__.py
  maintenance_stock/data/demo_maintenance_stock.xml
  maintenance_stock/hooks.py
  maintenance_stock/i18n/maintenance_stock.pot
  maintenance_stock/models/__init__.py
  maintenance_stock/models/maintenance_equipment.py
  maintenance_stock/models/maintenance_request.py
  maintenance_stock/models/stock_move.py
  maintenance_stock/models/stock_move_line.py
  maintenance_stock/models/stock_picking.py
  maintenance_stock/models/stock_warehouse.py
  maintenance_stock/readme/CONTRIBUTORS.rst
  maintenance_stock/readme/DESCRIPTION.rst
  maintenance_stock/readme/ROADMAP.rst
  maintenance_stock/readme/USAGE.rst
  maintenance_stock/static/description/equipment.png
  maintenance_stock/static/description/index.html
  maintenance_stock/static/description/move-line.png
  maintenance_stock/static/description/pick-1.png
  maintenance_stock/static/description/pick-2.png
  maintenance_stock/static/description/request-1.png
  maintenance_stock/static/img/toner.png
  maintenance_stock/tests/__init__.py
  maintenance_stock/tests/test_maintenance_stock.py
  maintenance_stock/views/maintenance_equipment_views.xml
  maintenance_stock/views/maintenance_request_views.xml
  maintenance_stock/views/stock_move_line_views.xml
  maintenance_stock/views/stock_move_views.xml
  maintenance_stock/views/stock_picking_views.xml
Labels: approved, bot is merging ⏳, ready to merge
