Repository OCA/maintenance, pull requests merged in 2021-10, with the labels that each got.

#162 [FIX] maintenance_plan: Remake the computation of next date
  maintenance_plan/models/maintenance_plan.py
Labels: approved, bot is merging ⏳

#164 [11.0][FIX] maintenance_plan: Remake the computation of next date
  maintenance_plan/models/maintenance_plan.py
Labels: approved, bot is merging ⏳

#165 [14.0][FIX] maintenance_plan: Remake the computation of next date
  maintenance_plan/models/maintenance_plan.py
Labels: approved, bot is merging ⏳

#167 [11.0][IMP] maintenance_plan: next maintenance date tweaks
  maintenance_plan/models/maintenance_plan.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: approved, bot is merging ⏳

#166 [12.0][FIX] maintenance_plan: Remake the computation of next date
  maintenance_plan/models/maintenance_plan.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: approved, bot is merging ⏳

#168 [13.0][IMP] maintenance_plan: next maintenance date tweaks
  maintenance_plan/models/maintenance_plan.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: bot is merging ⏳

#160 [14.0] [MIG] base_maintenance_config
  base_maintenance_config/README.rst
  base_maintenance_config/__init__.py
  base_maintenance_config/__manifest__.py
  base_maintenance_config/i18n/base_maintenance_config.pot
  base_maintenance_config/i18n/es.po
  base_maintenance_config/i18n/it.po
  base_maintenance_config/readme/CONFIGURE.rst
  base_maintenance_config/readme/CONTRIBUTORS.rst
  base_maintenance_config/readme/DESCRIPTION.rst
  base_maintenance_config/readme/USAGE.rst
  base_maintenance_config/static/description/icon.png
  base_maintenance_config/static/description/index.html
  base_maintenance_config/views/res_config_settings.xml
  setup/base_maintenance_config/odoo/addons/base_maintenance_config
  setup/base_maintenance_config/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#163 [14.0] [MIG] base_maintenance_group
  base_maintenance_group/README.rst
  base_maintenance_group/__init__.py
  base_maintenance_group/__manifest__.py
  base_maintenance_group/data/maintenance_data.xml
  base_maintenance_group/i18n/base_maintenance_group.pot
  base_maintenance_group/i18n/it.po
  base_maintenance_group/i18n/pt_BR.po
  base_maintenance_group/menuitems.xml
  base_maintenance_group/readme/CONTRIBUTORS.rst
  base_maintenance_group/readme/DESCRIPTION.rst
  base_maintenance_group/readme/USAGE.rst
  base_maintenance_group/security/maintenance_security.xml
  base_maintenance_group/static/description/icon.png
  base_maintenance_group/static/description/index.html
  setup/base_maintenance_group/odoo/addons/base_maintenance_group
  setup/base_maintenance_group/setup.py
Labels: bot is merging ⏳
