Repository OCA/maintenance, pull requests merged in 2021-11, with the labels that each got.

#174 [15.0][MIG] maintenance_equipment_sequence
  maintenance_equipment_sequence/README.rst
  maintenance_equipment_sequence/__init__.py
  maintenance_equipment_sequence/__manifest__.py
  maintenance_equipment_sequence/i18n/es.po
  maintenance_equipment_sequence/i18n/it.po
  maintenance_equipment_sequence/i18n/maintenance_equipment_sequence.pot
  maintenance_equipment_sequence/migrations/15.0.1.0.0/pre-migration.py
  maintenance_equipment_sequence/models/__init__.py
  maintenance_equipment_sequence/models/maintenance.py
  maintenance_equipment_sequence/readme/CONTRIBUTORS.rst
  maintenance_equipment_sequence/readme/DESCRIPTION.rst
  maintenance_equipment_sequence/static/description/icon.png
  maintenance_equipment_sequence/static/description/index.html
  maintenance_equipment_sequence/tests/__init__.py
  maintenance_equipment_sequence/tests/test_maintenance_equipment_sequence.py
  maintenance_equipment_sequence/views/maintenance_views.xml
  setup/maintenance_equipment_sequence/odoo/addons/maintenance_equipment_sequence
  setup/maintenance_equipment_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#175 [15.0][MIG] maintenance_plan_activity
  maintenance_plan_activity/README.rst
  maintenance_plan_activity/__init__.py
  maintenance_plan_activity/__manifest__.py
  maintenance_plan_activity/i18n/es.po
  maintenance_plan_activity/i18n/it.po
  maintenance_plan_activity/i18n/maintenance_plan_activity.pot
  maintenance_plan_activity/models/__init__.py
  maintenance_plan_activity/models/maintenance.py
  maintenance_plan_activity/models/maintenance_planned_activity.py
  maintenance_plan_activity/readme/CONTRIBUTORS.rst
  maintenance_plan_activity/readme/DESCRIPTION.rst
  maintenance_plan_activity/security/ir.model.access.csv
  maintenance_plan_activity/static/description/icon.png
  maintenance_plan_activity/static/description/index.html
  maintenance_plan_activity/static/description/maintenance_plan_activity.png
  maintenance_plan_activity/tests/__init__.py
  maintenance_plan_activity/tests/test_maintenance_plan_activity.py
  maintenance_plan_activity/views/maintenance_views.xml
  setup/maintenance_plan_activity/odoo/addons/maintenance_plan_activity
  setup/maintenance_plan_activity/setup.py
Labels: approved, bot is merging ⏳

#178 [11.0][FIX] maintenance_plan_activity: pass the res_model in the context so it is used in the team domain
  maintenance_plan_activity/models/maintenance.py
Labels: approved, bot is merging ⏳

#184 [12.0][FIX] base_maintenance_group: bug in security groups
  base_maintenance_group/security/maintenance_security.xml
Labels: bot is merging ⏳

#186 [13.0][FIX] base_maintenance_group: bug in security groups
  base_maintenance_group/security/maintenance_security.xml
Labels: bot is merging ⏳

#187 [14.0][FIX] base_maintenance_group: bug in security groups
  base_maintenance_group/security/maintenance_security.xml
Labels: bot is merging ⏳

#181 [15.0][FIX] maintenance_plan_activity: default activity team for maintenance request
  maintenance_plan_activity/models/maintenance.py
Labels: bot is merging ⏳

#183 [11.0][REF] convert get_relativedelta function to MaintenancePlan class method
  maintenance_plan/data/demo_maintenance_plan.xml
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/models/maintenance_plan.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: approved, ready to merge, bot is merging ⏳

#185 [11.0][FIX] base_maintenance_group: bug in security groups
  base_maintenance_group/security/maintenance_security.xml
Labels: bot is merging ⏳

#180 [14.0][FIX] maintenance_plan_activity: default activity team for maintenance requests
  maintenance_plan_activity/models/maintenance.py
Labels: bot is merging ⏳

#179 [13.0][FIX] maintenance_plan_activity: default activity team for maintenance requests
  maintenance_plan_activity/models/maintenance.py
Labels: bot is merging ⏳
