Repository OCA/maintenance, pull requests merged in 2022-01, with the labels that each got.

#209 [13.0][FIX] maintenance_plan: add rule migration
  maintenance_plan/migrations/13.0.1.2.4/noupdate_changes.xml
  maintenance_plan/migrations/13.0.1.2.4/post-migration.py
Labels: approved, bot is merging ⏳

#210 [13.0][FIX] maintencance_plan: add rule migration (fixup)
  maintenance_plan/migrations/13.0.1.2.4/post-migration.py
Labels: approved, bot is merging ⏳

#204 [13.0][FIX] maintenance_plan: fix new request date
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/models/maintenance_plan.py
Labels: approved, bot is merging ⏳

#201 [MIG] maintenance_remote: Migration to 14.0
  maintenance_remote/README.rst
  maintenance_remote/__init__.py
  maintenance_remote/__manifest__.py
  maintenance_remote/i18n/es.po
  maintenance_remote/i18n/fr.po
  maintenance_remote/i18n/it.po
  maintenance_remote/i18n/maintenance_remote.pot
  maintenance_remote/i18n/pt_BR.po
  maintenance_remote/models/__init__.py
  maintenance_remote/models/maintenance_request.py
  maintenance_remote/readme/CONTRIBUTORS.rst
  maintenance_remote/readme/DESCRIPTION.rst
  maintenance_remote/static/description/icon.png
  maintenance_remote/static/description/index.html
  maintenance_remote/views/maintenance_request.xml
  setup/maintenance_remote/odoo/addons/maintenance_remote
  setup/maintenance_remote/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#202 [11.0][FIX] maintenance_plan: fix new request date
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/tests/test_maintenance_plan.py
  maintenance_plan/views/maintenance_equipment_views.xml
Labels: approved, bot is merging ⏳

#211 [12.0][FIX] maintenance_plan: fix new request date
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/models/maintenance_plan.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: approved, bot is merging ⏳

#212 [15.0][FIX] maintenance_plan: fix new request date
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/tests/test_maintenance_plan.py
  maintenance_plan/views/maintenance_equipment_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#203 [14.0][FIX] maintenance_plan: fix new request date
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/tests/test_maintenance_plan.py
  maintenance_plan/views/maintenance_equipment_views.xml
Labels: bot is merging ⏳
