Repository OCA/maintenance, pull requests merged in 2022-10, with the labels that each got.

#241 [16.0][MIG] maintenance_equipment_hierarchy: Migration to 16.0
  maintenance_equipment_hierarchy/README.rst
  maintenance_equipment_hierarchy/__init__.py
  maintenance_equipment_hierarchy/__manifest__.py
  maintenance_equipment_hierarchy/data/demo_maintenance_equipment_hierarchy.xml
  maintenance_equipment_hierarchy/i18n/es.po
  maintenance_equipment_hierarchy/i18n/fr.po
  maintenance_equipment_hierarchy/i18n/it.po
  maintenance_equipment_hierarchy/i18n/maintenance_equipment_hierarchy.pot
  maintenance_equipment_hierarchy/models/__init__.py
  maintenance_equipment_hierarchy/models/maintenance_equipment.py
  maintenance_equipment_hierarchy/readme/CONTRIBUTORS.rst
  maintenance_equipment_hierarchy/readme/DESCRIPTION.rst
  maintenance_equipment_hierarchy/static/description/icon.png
  maintenance_equipment_hierarchy/static/description/index.html
  maintenance_equipment_hierarchy/tests/__init__.py
  maintenance_equipment_hierarchy/tests/test_maintenance_equipment_hierarchy.py
  maintenance_equipment_hierarchy/views/maintenance_equipment_views.xml
  setup/maintenance_equipment_hierarchy/odoo/addons/maintenance_equipment_hierarchy
  setup/maintenance_equipment_hierarchy/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#233 [14.0][FIX] maintenance_equipment_contract: fix access error
  maintenance_equipment_contract/models/maintenance_equipment.py
Labels: approved, ready to merge, bot is merging ⏳

#231 [14.0][FIX] maintenance_equipment_scrap: fix access rights errors
  maintenance_equipment_scrap/models/maintenance_equipment.py
  maintenance_equipment_scrap/security/ir.model.access.csv
  maintenance_equipment_scrap/tests/test_maintenance_equipment_scrap.py
Labels: approved, ready to merge, bot is merging ⏳, stale

#243 [15.0][FIX] maintenance_equipment_contract: fix access error (forward port)
  maintenance_equipment_contract/models/maintenance_equipment.py
Labels: bot is merging ⏳

#242 [12.0][FIX] maintenance_plan generate requests for inactive equipment
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: approved, ready to merge, bot is merging ⏳

#244 [13.0][FIX] maintenance_plan generate requests for inactive equipment
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: bot is merging ⏳

#245 [14.0][FIX] maintenance_plan inactive equipment maintenance creation
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: bot is merging ⏳

#246 [15.0][FIX] maintenance_plan create request for inactive equipments
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: bot is merging ⏳
