Repository OCA/maintenance, pull requests merged in 2022-03, with the labels that each got.

#196 [15.0][MIG] maintenance_equipment_status
  maintenance_equipment_status/README.rst
  maintenance_equipment_status/__init__.py
  maintenance_equipment_status/__manifest__.py
  maintenance_equipment_status/data/demo_maintenance_equipment_status.xml
  maintenance_equipment_status/i18n/es.po
  maintenance_equipment_status/i18n/it.po
  maintenance_equipment_status/i18n/maintenance_equipment_status.pot
  maintenance_equipment_status/models/__init__.py
  maintenance_equipment_status/models/maintenance_equipment.py
  maintenance_equipment_status/models/maintenance_equipment_status.py
  maintenance_equipment_status/readme/CONFIGURATION.rst
  maintenance_equipment_status/readme/CONTRIBUTORS.rst
  maintenance_equipment_status/readme/DESCRIPTION.rst
  maintenance_equipment_status/security/ir.model.access.csv
  maintenance_equipment_status/static/description/icon.png
  maintenance_equipment_status/static/description/index.html
  maintenance_equipment_status/views/maintenance_equipment_status_views.xml
  maintenance_equipment_status/views/maintenance_equipment_views.xml
  setup/maintenance_equipment_status/odoo/addons/maintenance_equipment_status
  setup/maintenance_equipment_status/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#208 [14.0][ADD] maintenance_equipment_image
  maintenance_equipment_image/README.rst
  maintenance_equipment_image/__init__.py
  maintenance_equipment_image/__manifest__.py
  maintenance_equipment_image/i18n/maintenance_equipment_image.pot
  maintenance_equipment_image/i18n/pt.po
  maintenance_equipment_image/models/__init__.py
  maintenance_equipment_image/models/maintenance_equipment.py
  maintenance_equipment_image/readme/CONTRIBUTORS.rst
  maintenance_equipment_image/readme/DESCRIPTION.rst
  maintenance_equipment_image/static/description/icon.png
  maintenance_equipment_image/static/description/index.html
  maintenance_equipment_image/views/maintenance_equipment_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#207 [14.0][IMP] maintenance_plan: improved embedded tree view labels
  maintenance_plan/views/maintenance_equipment_views.xml
Labels: approved, bot is merging ⏳

#217 [14.0][ADD] maintenance_product: New adon.
  maintenance_product/README.rst
  maintenance_product/__init__.py
  maintenance_product/__manifest__.py
  maintenance_product/i18n/es.po
  maintenance_product/i18n/maintenance_product.pot
  maintenance_product/models/__init__.py
  maintenance_product/models/maintenance_equipment.py
  maintenance_product/models/product_category.py
  maintenance_product/models/product_product.py
  maintenance_product/models/product_template.py
  maintenance_product/readme/CONTRIBUTORS.rst
  maintenance_product/readme/DESCRIPTION.rst
  maintenance_product/readme/USAGE.rst
  maintenance_product/static/description/icon.png
  maintenance_product/static/description/index.html
  maintenance_product/tests/__init__.py
  maintenance_product/tests/common.py
  maintenance_product/tests/test_maintenance_product.py
  maintenance_product/views/maintenance_equipment_view.xml
  maintenance_product/views/product_template_view.xml
  setup/maintenance_product/odoo/addons/maintenance_product
  setup/maintenance_product/setup.py
Labels: bot is merging ⏳

#219 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .t2d.yml
  README.md
  maintenance_equipment_sequence/models/maintenance.py
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/views/maintenance_equipment_views.xml
Labels: help wanted, needs review
