Repository OCA/maintenance, pull requests merged in 2022-12, with the labels that each got.

#264 [IMP] maintenance_account: only create Equipments on purchase documents
  maintenance_account/models/account_move.py
  maintenance_account/tests/test_maintenance_account.py
Labels: approved, bot is merging ⏳

#260 [16.0][IMP] maintenance_equipment_hierarchy - set unaccent to false on parent_path as proposed by warning logs
  maintenance_equipment_hierarchy/models/maintenance_equipment.py
Labels: approved, ready to merge

#267 [13.0][FIX] maintenance_plan: Display the maintenance_plan_ids field correctly.
  maintenance_plan/views/maintenance_equipment_views.xml
Labels: bot is merging ⏳

#269 [13.0][ADD] maintenance_timesheet_time_control: New module
  maintenance_timesheet_time_control/README.rst
  maintenance_timesheet_time_control/__init__.py
  maintenance_timesheet_time_control/__manifest__.py
  maintenance_timesheet_time_control/i18n/es.po
  maintenance_timesheet_time_control/i18n/maintenance_timesheet_time_control.pot
  maintenance_timesheet_time_control/models/__init__.py
  maintenance_timesheet_time_control/models/maintenance_request.py
  maintenance_timesheet_time_control/readme/CONTRIBUTORS.rst
  maintenance_timesheet_time_control/readme/DESCRIPTION.rst
  maintenance_timesheet_time_control/readme/INSTALL.rst
  maintenance_timesheet_time_control/readme/USAGE.rst
  maintenance_timesheet_time_control/static/description/icon.png
  maintenance_timesheet_time_control/static/description/index.html
  maintenance_timesheet_time_control/tests/__init__.py
  maintenance_timesheet_time_control/tests/test_maintenance_timesheet_time_control.py
  maintenance_timesheet_time_control/views/maintenance_request_view.xml
  maintenance_timesheet_time_control/wizards/__init__.py
  maintenance_timesheet_time_control/wizards/hr_timesheet_switch.py
  setup/maintenance_timesheet_time_control/odoo/addons/maintenance_timesheet_time_control
  setup/maintenance_timesheet_time_control/setup.py
Labels: approved, bot is merging ⏳

#253 [15.0][REF] moving function get_relativedelta to method
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/models/maintenance_plan.py
  maintenance_plan/tests/test_maintenance_plan.py
  maintenance_plan/views/maintenance_equipment_views.xml
Labels: bot is merging ⏳

#247 [13.0][ADD] maintenance_request_stage_transition: add team_ids tags in stages
  maintenance_request_stage_transition/models/__init__.py
  maintenance_request_stage_transition/models/maintenance_stage.py
  maintenance_request_stage_transition/models/maintenance_team.py
  maintenance_request_stage_transition/views/maintenance_stage.xml
Labels: approved, bot is merging ⏳

#270 [13.0][IMP] maintenance_timesheet: Add timesheet page from maintenance request form view.
  base_maintenance/views/maintenance_request_views.xml
  maintenance_timesheet/__manifest__.py
  maintenance_timesheet/migrations/13.0.1.2.0/pre-migration.py
  maintenance_timesheet/models/maintenance_request.py
  maintenance_timesheet/views/maintenance_request_views.xml
  maintenance_timesheet_time_control/views/maintenance_request_view.xml
Labels: approved, bot is merging ⏳

#272 [13.0][FIX] maintenance_plan: Avoid multiple notebooks
  maintenance_plan/__manifest__.py
  maintenance_plan/views/maintenance_equipment_views.xml
Labels: approved, bot is merging ⏳

#271 [14.0][IMP] maintenance_timesheet: Add timesheet page from maintenance request form view.
  base_maintenance/views/maintenance_request_views.xml
  maintenance_timesheet/__manifest__.py
  maintenance_timesheet/migrations/14.0.2.0.0/pre-migration.py
  maintenance_timesheet/models/maintenance_request.py
  maintenance_timesheet/views/maintenance_request_views.xml
Labels: approved, bot is merging ⏳

#266 [16.0][MIG] base_maintenance: Migration to 16.0
  base_maintenance/README.rst
  base_maintenance/__init__.py
  base_maintenance/__manifest__.py
  base_maintenance/i18n/base_maintenance.pot
  base_maintenance/i18n/it.po
  base_maintenance/i18n/pt.po
  base_maintenance/i18n/pt_BR.po
  base_maintenance/models/__init__.py
  base_maintenance/models/maintenance_team.py
  base_maintenance/readme/CONTRIBUTORS.rst
  base_maintenance/readme/DESCRIPTION.rst
  base_maintenance/static/description/icon.png
  base_maintenance/static/description/index.html
  base_maintenance/views/maintenance_equipment_views.xml
  base_maintenance/views/maintenance_request_views.xml
  base_maintenance/views/maintenance_team_views.xml
  base_maintenance/views/report_maintenance_request.xml
  setup/base_maintenance/odoo/addons/base_maintenance
  setup/base_maintenance/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#254 [15.0][MIG] base maintenance config: Migration to 15.0
  base_maintenance_config/README.rst
  base_maintenance_config/__init__.py
  base_maintenance_config/__manifest__.py
  base_maintenance_config/i18n/base_maintenance_config.pot
  base_maintenance_config/i18n/es.po
  base_maintenance_config/i18n/it.po
  base_maintenance_config/readme/CONFIGURE.rst
  base_maintenance_config/readme/CONTRIBUTORS.rst
  base_maintenance_config/readme/DESCRIPTION.rst
  base_maintenance_config/readme/USAGE.rst
  base_maintenance_config/static/description/icon.png
  base_maintenance_config/static/description/index.html
  base_maintenance_config/views/res_config_settings.xml
  setup/base_maintenance_config/odoo/addons/base_maintenance_config
  setup/base_maintenance_config/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#255 [15.0][MIG] base_maintenance_group: Migration to 15.0
  base_maintenance_group/README.rst
  base_maintenance_group/__init__.py
  base_maintenance_group/__manifest__.py
  base_maintenance_group/data/maintenance_data.xml
  base_maintenance_group/i18n/base_maintenance_group.pot
  base_maintenance_group/i18n/it.po
  base_maintenance_group/i18n/pt_BR.po
  base_maintenance_group/menuitems.xml
  base_maintenance_group/readme/CONTRIBUTORS.rst
  base_maintenance_group/readme/DESCRIPTION.rst
  base_maintenance_group/readme/USAGE.rst
  base_maintenance_group/security/maintenance_security.xml
  base_maintenance_group/static/description/icon.png
  base_maintenance_group/static/description/index.html
  setup/base_maintenance_group/odoo/addons/base_maintenance_group
  setup/base_maintenance_group/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#262 [16.0][FIX] maintenance_equipment_hierarchy - children smartbutton leads wrongly to parent equipment
  maintenance_equipment_hierarchy/models/maintenance_equipment.py
Labels: approved, ready to merge, bot is merging ⏳

#256 [15.0][MIG] maintenance_product: Migration to 15.0
  maintenance_product/README.rst
  maintenance_product/__init__.py
  maintenance_product/__manifest__.py
  maintenance_product/i18n/es.po
  maintenance_product/i18n/it.po
  maintenance_product/i18n/maintenance_product.pot
  maintenance_product/models/__init__.py
  maintenance_product/models/maintenance_equipment.py
  maintenance_product/models/product_category.py
  maintenance_product/models/product_product.py
  maintenance_product/models/product_template.py
  maintenance_product/readme/CONTRIBUTORS.rst
  maintenance_product/readme/DESCRIPTION.rst
  maintenance_product/readme/USAGE.rst
  maintenance_product/static/description/icon.png
  maintenance_product/static/description/index.html
  maintenance_product/tests/__init__.py
  maintenance_product/tests/common.py
  maintenance_product/tests/test_maintenance_product.py
  maintenance_product/views/maintenance_equipment_view.xml
  maintenance_product/views/product_template_view.xml
  setup/maintenance_product/odoo/addons/maintenance_product
  setup/maintenance_product/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#263 [ADD] maintenance_purchase
  maintenance_purchase/README.rst
  maintenance_purchase/__init__.py
  maintenance_purchase/__manifest__.py
  maintenance_purchase/models/__init__.py
  maintenance_purchase/models/maintenance_equipment.py
  maintenance_purchase/models/purchase_order.py
  maintenance_purchase/readme/CONTRIBUTORS.rst
  maintenance_purchase/readme/DESCRIPTION.rst
  maintenance_purchase/static/description/icon.png
  maintenance_purchase/views/maintenance_equipment.xml
  maintenance_purchase/views/purchase_order.xml
  setup/maintenance_purchase/odoo/addons/maintenance_purchase
  setup/maintenance_purchase/setup.py
Labels: approved, bot is merging ⏳

#258 [15.0][mig] maintenance_equipment_scrap: Migration to 15.0
  maintenance_equipment_scrap/README.rst
  maintenance_equipment_scrap/__init__.py
  maintenance_equipment_scrap/__manifest__.py
  maintenance_equipment_scrap/data/maintenance_data.xml
  maintenance_equipment_scrap/i18n/es.po
  maintenance_equipment_scrap/i18n/it.po
  maintenance_equipment_scrap/i18n/maintenance_equipment_scrap.pot
  maintenance_equipment_scrap/i18n/zh_CN.po
  maintenance_equipment_scrap/models/__init__.py
  maintenance_equipment_scrap/models/maintenance_equipment.py
  maintenance_equipment_scrap/models/maintenance_equipment_category.py
  maintenance_equipment_scrap/readme/CONTRIBUTORS.rst
  maintenance_equipment_scrap/readme/DESCRIPTION.rst
  maintenance_equipment_scrap/security/ir.model.access.csv
  maintenance_equipment_scrap/static/description/icon.png
  maintenance_equipment_scrap/static/description/index.html
  maintenance_equipment_scrap/tests/__init__.py
  maintenance_equipment_scrap/tests/test_maintenance_equipment_scrap.py
  maintenance_equipment_scrap/views/maintenance_equipment.xml
  maintenance_equipment_scrap/views/maintenance_equipment_category.xml
  maintenance_equipment_scrap/wizard/__init__.py
  maintenance_equipment_scrap/wizard/scrap_equipment.py
  maintenance_equipment_scrap/wizard/scrap_equipment.xml
  setup/maintenance_equipment_scrap/odoo/addons/maintenance_equipment_scrap
  setup/maintenance_equipment_scrap/setup.py
Labels: approved, ready to merge, bot is merging ⏳
