Repository OCA/maintenance, pull requests merged in 2023-04, with the labels that each got.

#326 [13.0][IMP] maintenance_plan: Add rules to maintenance.plan to view records of the equipments they follow
  maintenance_plan/security/maintenance_security.xml
Labels: approved, bot is merging ⏳

#331 [14.0][IMP] maintenance_plan: Add rules to maintenance.plan to view records of the equipments they follow
  maintenance_plan/security/maintenance_security.xml
Labels: bot is merging ⏳

#328 [14.0][IMP] maintenandce_equipment_image: Add zoom
  maintenance_equipment_image/views/maintenance_equipment_views.xml
Labels: approved, ready to merge, bot is merging ⏳
