Repository OCA/maintenance, pull requests merged in 2023-03, with the labels that each got.

#310 [13.0][FIX] maintenance_account: Avoid error when post the invoice if the user does not have permissions to create maintenance records.
  maintenance_account/models/account_move.py
  maintenance_account/tests/test_maintenance_account.py
Labels: approved, bot is merging ⏳

#307 [13.0][IMP] maintenance_plan: Skip assigned mail + Activity mail of the requests created from plans
  maintenance_plan/i18n/es.po
  maintenance_plan/i18n/maintenance_plan.pot
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/models/maintenance_plan.py
  maintenance_plan/views/maintenance_plan_views.xml
Labels: approved, bot is merging ⏳

#315 [14.0][IMP] maintenance_plan: Skip assigned mail + Activity mail of the requests created from plans
  maintenance_plan/i18n/es.po
  maintenance_plan/i18n/maintenance_plan.pot
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/models/maintenance_plan.py
  maintenance_plan/views/maintenance_plan_views.xml
Labels: approved, bot is merging ⏳

#311 [14.0][FIX] maintenance_account: Avoid error when post the invoice if the user does not have permissions to create maintenance records
  maintenance_account/models/account_move.py
  maintenance_account/tests/test_maintenance_account.py
Labels: approved, bot is merging ⏳

#313 [13.0][IMP] maintenance_plan_employee: Add employees to maintenance request report
  maintenance_plan_employee/__manifest__.py
  maintenance_plan_employee/i18n/es.po
  maintenance_plan_employee/i18n/maintenance_plan_employee.pot
  maintenance_plan_employee/tests/test_maintenance_plan_employee.py
  maintenance_plan_employee/views/report_maintenance_request.xml
Labels: approved, bot is merging ⏳

#314 [15.0][MIG] maintenance_request_employee: Migration to 15.0
  maintenance_request_employee/README.rst
  maintenance_request_employee/__init__.py
  maintenance_request_employee/__manifest__.py
  maintenance_request_employee/i18n/es.po
  maintenance_request_employee/i18n/maintenance_request_employee.pot
  maintenance_request_employee/models/__init__.py
  maintenance_request_employee/models/maintenance_request.py
  maintenance_request_employee/readme/CONTRIBUTORS.rst
  maintenance_request_employee/readme/DESCRIPTION.rst
  maintenance_request_employee/static/description/icon.png
  maintenance_request_employee/static/description/icon.svg
  maintenance_request_employee/static/description/index.html
  maintenance_request_employee/views/maintenance_request_views.xml
  setup/maintenance_request_employee/odoo/addons/maintenance_request_employee
  setup/maintenance_request_employee/setup.py
Labels: approved, bot is merging ⏳

#316 [15.0][IMP] maintenance_plan: Skip assigned mail + Activity mail of the requests created from plans
  maintenance_plan/i18n/es.po
  maintenance_plan/i18n/maintenance_plan.pot
  maintenance_plan/models/maintenance_equipment.py
  maintenance_plan/models/maintenance_plan.py
  maintenance_plan/views/maintenance_plan_views.xml
Labels: approved, bot is merging ⏳

#318 [14.0][IMP] maintenance_plan: Change tests to allow inheritance
  maintenance_plan/tests/common.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: bot is merging ⏳

#319 [15.0][IMP] maintenance_plan: Change tests to allow inheritance
  maintenance_plan/tests/common.py
  maintenance_plan/tests/test_maintenance_plan.py
Labels: bot is merging ⏳

#317 [15.0][MIG] maintenance_plan_employee: Migration to 15.0
  maintenance_plan_employee/README.rst
  maintenance_plan_employee/__init__.py
  maintenance_plan_employee/__manifest__.py
  maintenance_plan_employee/i18n/es.po
  maintenance_plan_employee/i18n/maintenance_plan_employee.pot
  maintenance_plan_employee/models/__init__.py
  maintenance_plan_employee/models/maintenance_equipment.py
  maintenance_plan_employee/models/maintenance_plan.py
  maintenance_plan_employee/readme/CONTRIBUTORS.rst
  maintenance_plan_employee/readme/DESCRIPTION.rst
  maintenance_plan_employee/static/description/icon.png
  maintenance_plan_employee/static/description/index.html
  maintenance_plan_employee/tests/__init__.py
  maintenance_plan_employee/tests/test_maintenance_plan_employee.py
  maintenance_plan_employee/views/maintenance_plan_views.xml
  maintenance_plan_employee/views/report_maintenance_request.xml
  setup/maintenance_plan_employee/odoo/addons/maintenance_plan_employee
  setup/maintenance_plan_employee/setup.py
Labels: approved, bot is merging ⏳

#309 [14.0][FIX] maintenance_account /maintenance_purchase: check before creation
  maintenance_account/models/account_move.py
  maintenance_purchase/models/purchase_order.py
Labels: bot is merging ⏳

#312 [15.0][MIG] maintenance_account: Migration to 15.0
  maintenance_account/README.rst
  maintenance_account/__init__.py
  maintenance_account/__manifest__.py
  maintenance_account/i18n/es.po
  maintenance_account/i18n/it.po
  maintenance_account/i18n/maintenance_account.pot
  maintenance_account/models/__init__.py
  maintenance_account/models/account_move.py
  maintenance_account/models/maintenance_equipment.py
  maintenance_account/readme/CONTRIBUTORS.rst
  maintenance_account/readme/DESCRIPTION.rst
  maintenance_account/readme/USAGE.rst
  maintenance_account/static/description/icon.png
  maintenance_account/static/description/index.html
  maintenance_account/tests/__init__.py
  maintenance_account/tests/test_maintenance_account.py
  maintenance_account/views/account_move_view.xml
  maintenance_account/views/maintenance_equipment_view.xml
  setup/maintenance_account/odoo/addons/maintenance_account
  setup/maintenance_account/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#320 [14.0][MIG] maintenance_request_repair: Migration to 14.0
  maintenance_request_repair/README.rst
  maintenance_request_repair/__init__.py
  maintenance_request_repair/__manifest__.py
  maintenance_request_repair/i18n/it.po
  maintenance_request_repair/i18n/maintenance_request_repair.pot
  maintenance_request_repair/i18n/pt_BR.po
  maintenance_request_repair/models/__init__.py
  maintenance_request_repair/models/maintenance_request.py
  maintenance_request_repair/models/repair_order.py
  maintenance_request_repair/readme/CONTRIBUTORS.rst
  maintenance_request_repair/readme/DESCRIPTION.rst
  maintenance_request_repair/readme/USAGE.rst
  maintenance_request_repair/static/description/icon.png
  maintenance_request_repair/static/description/index.html
  maintenance_request_repair/tests/__init__.py
  maintenance_request_repair/tests/test_repair_order.py
  maintenance_request_repair/views/maintenance_request.xml
  maintenance_request_repair/views/repair_order.xml
  setup/maintenance_request_repair/odoo/addons/maintenance_request_repair
  setup/maintenance_request_repair/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#322 [MIG] maintenance_request_repair: Migration to 15.0
  maintenance_request_repair/README.rst
  maintenance_request_repair/__init__.py
  maintenance_request_repair/__manifest__.py
  maintenance_request_repair/i18n/it.po
  maintenance_request_repair/i18n/maintenance_request_repair.pot
  maintenance_request_repair/i18n/pt_BR.po
  maintenance_request_repair/models/__init__.py
  maintenance_request_repair/models/maintenance_request.py
  maintenance_request_repair/models/repair_order.py
  maintenance_request_repair/readme/CONTRIBUTORS.rst
  maintenance_request_repair/readme/DESCRIPTION.rst
  maintenance_request_repair/readme/USAGE.rst
  maintenance_request_repair/static/description/icon.png
  maintenance_request_repair/static/description/index.html
  maintenance_request_repair/tests/__init__.py
  maintenance_request_repair/tests/test_repair_order.py
  maintenance_request_repair/views/maintenance_request.xml
  maintenance_request_repair/views/repair_order.xml
  setup/maintenance_request_repair/odoo/addons/maintenance_request_repair
  setup/maintenance_request_repair/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳
