Repository OCA/maintenance, pull requests merged in 2023-06, with the labels that each got.

#338 [16.0][MIG] maintenance_project
  maintenance_project/README.rst
  maintenance_project/__init__.py
  maintenance_project/__manifest__.py
  maintenance_project/data/demo_maintenance_project.xml
  maintenance_project/i18n/es.po
  maintenance_project/i18n/it.po
  maintenance_project/i18n/maintenance_project.pot
  maintenance_project/models/__init__.py
  maintenance_project/models/maintenance_equipment.py
  maintenance_project/models/maintenance_request.py
  maintenance_project/models/project_project.py
  maintenance_project/readme/CONTRIBUTORS.rst
  maintenance_project/readme/DESCRIPTION.rst
  maintenance_project/report/maintenance_request_report.xml
  maintenance_project/security/maintenance_project_security.xml
  maintenance_project/static/description/icon.png
  maintenance_project/static/description/index.html
  maintenance_project/tests/__init__.py
  maintenance_project/tests/test_maintenance_project.py
  maintenance_project/views/maintenance_equipment_views.xml
  maintenance_project/views/maintenance_request_views.xml
  maintenance_project/views/project_project_views.xml
  setup/maintenance_project/odoo/addons/maintenance_project
  setup/maintenance_project/setup.py
Labels: approved, bot is merging ⏳

#340 [16.0][MIG] maintenance_request_sequence
  maintenance_request_sequence/README.rst
  maintenance_request_sequence/__init__.py
  maintenance_request_sequence/__manifest__.py
  maintenance_request_sequence/data/maintenance_request_data.xml
  maintenance_request_sequence/i18n/es.po
  maintenance_request_sequence/i18n/it.po
  maintenance_request_sequence/i18n/maintenance_request_sequence.pot
  maintenance_request_sequence/i18n/pt_BR.po
  maintenance_request_sequence/models/__init__.py
  maintenance_request_sequence/models/maintenance_request.py
  maintenance_request_sequence/models/maintenance_team.py
  maintenance_request_sequence/readme/CONTRIBUTORS.rst
  maintenance_request_sequence/readme/DESCRIPTION.rst
  maintenance_request_sequence/static/description/icon.png
  maintenance_request_sequence/static/description/index.html
  maintenance_request_sequence/tests/__init__.py
  maintenance_request_sequence/tests/test_maintenance_request_sequence.py
  maintenance_request_sequence/views/maintenance_request.xml
  maintenance_request_sequence/views/maintenance_team.xml
  setup/maintenance_request_sequence/odoo/addons/maintenance_request_sequence
  setup/maintenance_request_sequence/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#284 [16.0][MIG] maintenance_equipment_image: Migration to 16.0
  maintenance_equipment_image/README.rst
  maintenance_equipment_image/__init__.py
  maintenance_equipment_image/__manifest__.py
  maintenance_equipment_image/i18n/it.po
  maintenance_equipment_image/i18n/maintenance_equipment_image.pot
  maintenance_equipment_image/i18n/pt.po
  maintenance_equipment_image/models/__init__.py
  maintenance_equipment_image/models/maintenance_equipment.py
  maintenance_equipment_image/readme/CONTRIBUTORS.rst
  maintenance_equipment_image/readme/DESCRIPTION.rst
  maintenance_equipment_image/static/description/icon.png
  maintenance_equipment_image/static/description/index.html
  maintenance_equipment_image/views/maintenance_equipment_views.xml
  setup/maintenance_equipment_image/odoo/addons/maintenance_equipment_image
  setup/maintenance_equipment_image/setup.py
Labels: approved, ready to merge, bot is merging ⏳, stale
