Repository OCA/maintenance, pull requests merged in 2023-07, with the labels that each got.

#345 [16.0][MIG] maintenance_equipment_tags: Migration to 16.0
  maintenance_equipment_tags/README.rst
  maintenance_equipment_tags/__init__.py
  maintenance_equipment_tags/__manifest__.py
  maintenance_equipment_tags/demo/maintenance_equipment_tags_demo.xml
  maintenance_equipment_tags/i18n/es.po
  maintenance_equipment_tags/i18n/it.po
  maintenance_equipment_tags/i18n/maintenance_equipment_tags.pot
  maintenance_equipment_tags/i18n/pt.po
  maintenance_equipment_tags/i18n/pt_BR.po
  maintenance_equipment_tags/models/__init__.py
  maintenance_equipment_tags/models/maintenance_equipment.py
  maintenance_equipment_tags/models/maintenance_equipment_tag.py
  maintenance_equipment_tags/readme/CONTRIBUTORS.rst
  maintenance_equipment_tags/readme/DESCRIPTION.rst
  maintenance_equipment_tags/security/ir.model.access.csv
  maintenance_equipment_tags/static/description/icon.png
  maintenance_equipment_tags/static/description/index.html
  maintenance_equipment_tags/views/maintenance_equipment.xml
  maintenance_equipment_tags/views/maintenance_equipment_tag.xml
  setup/maintenance_equipment_tags/odoo/addons/maintenance_equipment_tags
  setup/maintenance_equipment_tags/setup.py
Labels: approved, bot is merging ⏳

#346 [16.0][MIG] maintenance_request_stage_transition: Migration to 16.0
  maintenance_request_stage_transition/README.rst
  maintenance_request_stage_transition/__init__.py
  maintenance_request_stage_transition/__manifest__.py
  maintenance_request_stage_transition/data/demo_maintenance_request_stage_transition.xml
  maintenance_request_stage_transition/i18n/es.po
  maintenance_request_stage_transition/i18n/it.po
  maintenance_request_stage_transition/i18n/maintenance_request_stage_transition.pot
  maintenance_request_stage_transition/models/__init__.py
  maintenance_request_stage_transition/models/maintenance_request.py
  maintenance_request_stage_transition/models/maintenance_stage.py
  maintenance_request_stage_transition/readme/CONTRIBUTORS.rst
  maintenance_request_stage_transition/readme/DESCRIPTION.rst
  maintenance_request_stage_transition/readme/USAGE.rst
  maintenance_request_stage_transition/static/description/icon.png
  maintenance_request_stage_transition/static/description/index.html
  maintenance_request_stage_transition/tests/__init__.py
  maintenance_request_stage_transition/tests/test_flow.py
  maintenance_request_stage_transition/views/maintenance_request.xml
  maintenance_request_stage_transition/views/maintenance_stage.xml
  setup/maintenance_request_stage_transition/odoo/addons/maintenance_request_stage_transition
  setup/maintenance_request_stage_transition/setup.py
Labels: approved, bot is merging ⏳

#344 [16.0] [MIG] base_maintenance_group
  base_maintenance_group/README.rst
  base_maintenance_group/__init__.py
  base_maintenance_group/__manifest__.py
  base_maintenance_group/data/maintenance_data.xml
  base_maintenance_group/i18n/base_maintenance_group.pot
  base_maintenance_group/i18n/it.po
  base_maintenance_group/i18n/pt_BR.po
  base_maintenance_group/menuitems.xml
  base_maintenance_group/readme/CONTRIBUTORS.rst
  base_maintenance_group/readme/DESCRIPTION.rst
  base_maintenance_group/readme/USAGE.rst
  base_maintenance_group/security/maintenance_security.xml
  base_maintenance_group/static/description/icon.png
  base_maintenance_group/static/description/index.html
  setup/base_maintenance_group/odoo/addons/base_maintenance_group
  setup/base_maintenance_group/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#343 [16.0] [MIG] maintenance_equipment_contract
  maintenance_equipment_contract/README.rst
  maintenance_equipment_contract/__init__.py
  maintenance_equipment_contract/__manifest__.py
  maintenance_equipment_contract/demo/maintenance_equipment_contract_demo.xml
  maintenance_equipment_contract/i18n/es.po
  maintenance_equipment_contract/i18n/it.po
  maintenance_equipment_contract/i18n/maintenance_equipment_contract.pot
  maintenance_equipment_contract/i18n/pt_BR.po
  maintenance_equipment_contract/models/__init__.py
  maintenance_equipment_contract/models/contract_contract.py
  maintenance_equipment_contract/models/maintenance_equipment.py
  maintenance_equipment_contract/readme/CONTRIBUTORS.rst
  maintenance_equipment_contract/readme/DESCRIPTION.rst
  maintenance_equipment_contract/static/description/icon.png
  maintenance_equipment_contract/static/description/index.html
  maintenance_equipment_contract/tests/__init__.py
  maintenance_equipment_contract/tests/test_equipment_contract.py
  maintenance_equipment_contract/views/contract_contract.xml
  maintenance_equipment_contract/views/maintenance_equipment.xml
  setup/maintenance_equipment_contract/odoo/addons/maintenance_equipment_contract
  setup/maintenance_equipment_contract/setup.py
Labels: approved, bot is merging ⏳

#342 [16.0][MIG] maintenance_product: Migration to 16.0
  maintenance_product/README.rst
  maintenance_product/__init__.py
  maintenance_product/__manifest__.py
  maintenance_product/i18n/es.po
  maintenance_product/i18n/it.po
  maintenance_product/i18n/maintenance_product.pot
  maintenance_product/models/__init__.py
  maintenance_product/models/maintenance_equipment.py
  maintenance_product/models/product_category.py
  maintenance_product/models/product_product.py
  maintenance_product/models/product_template.py
  maintenance_product/readme/CONTRIBUTORS.rst
  maintenance_product/readme/DESCRIPTION.rst
  maintenance_product/readme/USAGE.rst
  maintenance_product/static/description/icon.png
  maintenance_product/static/description/index.html
  maintenance_product/tests/__init__.py
  maintenance_product/tests/common.py
  maintenance_product/tests/test_maintenance_product.py
  maintenance_product/views/maintenance_equipment_view.xml
  maintenance_product/views/product_template_view.xml
  setup/maintenance_product/odoo/addons/maintenance_product
  setup/maintenance_product/setup.py
Labels: approved, bot is merging ⏳

#341 [16.0][MIG] maintenance_equipment_status
  maintenance_equipment_status/README.rst
  maintenance_equipment_status/__init__.py
  maintenance_equipment_status/__manifest__.py
  maintenance_equipment_status/data/demo_maintenance_equipment_status.xml
  maintenance_equipment_status/i18n/es.po
  maintenance_equipment_status/i18n/it.po
  maintenance_equipment_status/i18n/maintenance_equipment_status.pot
  maintenance_equipment_status/models/__init__.py
  maintenance_equipment_status/models/maintenance_equipment.py
  maintenance_equipment_status/models/maintenance_equipment_status.py
  maintenance_equipment_status/readme/CONFIGURATION.rst
  maintenance_equipment_status/readme/CONTRIBUTORS.rst
  maintenance_equipment_status/readme/DESCRIPTION.rst
  maintenance_equipment_status/security/ir.model.access.csv
  maintenance_equipment_status/static/description/icon.png
  maintenance_equipment_status/static/description/index.html
  maintenance_equipment_status/views/maintenance_equipment_status_views.xml
  maintenance_equipment_status/views/maintenance_equipment_views.xml
  setup/maintenance_equipment_status/odoo/addons/maintenance_equipment_status
  setup/maintenance_equipment_status/setup.py
Labels: bot is merging ⏳

#323 [16.0][MIG] maintenance_request_repair: Migration to 16.0
  maintenance_request_repair/README.rst
  maintenance_request_repair/__init__.py
  maintenance_request_repair/__manifest__.py
  maintenance_request_repair/i18n/it.po
  maintenance_request_repair/i18n/maintenance_request_repair.pot
  maintenance_request_repair/i18n/pt_BR.po
  maintenance_request_repair/models/__init__.py
  maintenance_request_repair/models/maintenance_request.py
  maintenance_request_repair/models/repair_order.py
  maintenance_request_repair/readme/CONTRIBUTORS.rst
  maintenance_request_repair/readme/DESCRIPTION.rst
  maintenance_request_repair/readme/USAGE.rst
  maintenance_request_repair/static/description/icon.png
  maintenance_request_repair/static/description/index.html
  maintenance_request_repair/tests/__init__.py
  maintenance_request_repair/tests/test_repair_order.py
  maintenance_request_repair/views/maintenance_request.xml
  maintenance_request_repair/views/repair_order.xml
  setup/maintenance_request_repair/odoo/addons/maintenance_request_repair
  setup/maintenance_request_repair/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#337 [13.0][MIG] maintenance_stock: Migration to 13.0
  maintenance_stock/README.rst
  maintenance_stock/__init__.py
  maintenance_stock/__manifest__.py
  maintenance_stock/data/demo_maintenance_stock.xml
  maintenance_stock/hooks.py
  maintenance_stock/i18n/es.po
  maintenance_stock/i18n/it.po
  maintenance_stock/i18n/maintenance_stock.pot
  maintenance_stock/i18n/pt_BR.po
  maintenance_stock/models/__init__.py
  maintenance_stock/models/maintenance_equipment.py
  maintenance_stock/models/maintenance_request.py
  maintenance_stock/models/stock_move.py
  maintenance_stock/models/stock_move_line.py
  maintenance_stock/models/stock_picking.py
  maintenance_stock/models/stock_warehouse.py
  maintenance_stock/readme/CONTRIBUTORS.rst
  maintenance_stock/readme/DESCRIPTION.rst
  maintenance_stock/readme/ROADMAP.rst
  maintenance_stock/readme/USAGE.rst
  maintenance_stock/static/description/equipment.png
  maintenance_stock/static/description/icon.png
  maintenance_stock/static/description/index.html
  maintenance_stock/static/description/move-line.png
  maintenance_stock/static/description/pick-1.png
  maintenance_stock/static/description/pick-2.png
  maintenance_stock/static/description/request-1.png
  maintenance_stock/static/img/toner.png
  maintenance_stock/tests/__init__.py
  maintenance_stock/tests/test_maintenance_stock.py
  maintenance_stock/views/maintenance_equipment_views.xml
  maintenance_stock/views/maintenance_request_views.xml
  maintenance_stock/views/stock_move_line_views.xml
  maintenance_stock/views/stock_move_views.xml
  maintenance_stock/views/stock_picking_views.xml
  setup/maintenance_stock/odoo/addons/maintenance_stock
  setup/maintenance_stock/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#349 [16.0][MIG] maintenance_team_hierarchy: Migration to 16.0
  maintenance_team_hierarchy/README.rst
  maintenance_team_hierarchy/__init__.py
  maintenance_team_hierarchy/__manifest__.py
  maintenance_team_hierarchy/demo/maintenance_request_demo.xml
  maintenance_team_hierarchy/demo/maintenance_team_demo.xml
  maintenance_team_hierarchy/i18n/es.po
  maintenance_team_hierarchy/i18n/it.po
  maintenance_team_hierarchy/i18n/maintenance_team_hierarchy.pot
  maintenance_team_hierarchy/i18n/pt_BR.po
  maintenance_team_hierarchy/models/__init__.py
  maintenance_team_hierarchy/models/maintenance_team.py
  maintenance_team_hierarchy/readme/CONTRIBUTORS.rst
  maintenance_team_hierarchy/readme/DESCRIPTION.rst
  maintenance_team_hierarchy/static/description/icon.png
  maintenance_team_hierarchy/static/description/index.html
  maintenance_team_hierarchy/tests/__init__.py
  maintenance_team_hierarchy/tests/test_team_hierarchy.py
  maintenance_team_hierarchy/views/maintenance_team.xml
  setup/maintenance_team_hierarchy/odoo/addons/maintenance_team_hierarchy
  setup/maintenance_team_hierarchy/setup.py
Labels: approved, ready to merge

#350 [15.0][ADD] maintenance_security: New module
  maintenance_security/README.rst
  maintenance_security/__init__.py
  maintenance_security/__manifest__.py
  maintenance_security/i18n/es.po
  maintenance_security/i18n/maintenance_security.pot
  maintenance_security/models/__init__.py
  maintenance_security/models/mail_followers.py
  maintenance_security/readme/CONTRIBUTORS.rst
  maintenance_security/readme/DESCRIPTION.rst
  maintenance_security/static/description/icon.png
  maintenance_security/static/description/index.html
  maintenance_security/tests/__init__.py
  maintenance_security/tests/test_maintenance_security.py
  maintenance_security/views/maintenance_views.xml
  setup/maintenance_security/odoo/addons/maintenance_security
  setup/maintenance_security/setup.py
Labels: approved, bot is merging ⏳
