Repository OCA/maintenance, pull requests merged in 2024-04, with the labels that each got.

#388 [16.0][MIG] maintenance_purchase
  maintenance_purchase/README.rst
  maintenance_purchase/__init__.py
  maintenance_purchase/__manifest__.py
  maintenance_purchase/i18n/es.po
  maintenance_purchase/i18n/it.po
  maintenance_purchase/i18n/maintenance_purchase.pot
  maintenance_purchase/models/__init__.py
  maintenance_purchase/models/maintenance_equipment.py
  maintenance_purchase/models/purchase_order.py
  maintenance_purchase/readme/CONTRIBUTORS.rst
  maintenance_purchase/readme/DESCRIPTION.rst
  maintenance_purchase/static/description/icon.png
  maintenance_purchase/static/description/index.html
  maintenance_purchase/tests/__init__.py
  maintenance_purchase/tests/test_purchase_order.py
  maintenance_purchase/views/maintenance_equipment.xml
  maintenance_purchase/views/purchase_order.xml
  setup/maintenance_purchase/odoo/addons/maintenance_purchase
  setup/maintenance_purchase/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#378 [ADD] maintenance_equipment_meter
  maintenance_equipment_meter/README.rst
  maintenance_equipment_meter/__init__.py
  maintenance_equipment_meter/__manifest__.py
  maintenance_equipment_meter/models/__init__.py
  maintenance_equipment_meter/models/maintenance_equipment.py
  maintenance_equipment_meter/models/maintenance_equipment_meter.py
  maintenance_equipment_meter/models/maintenance_request.py
  maintenance_equipment_meter/readme/CONTRIBUTORS.md
  maintenance_equipment_meter/readme/DESCRIPTION.md
  maintenance_equipment_meter/security/ir.model.access.csv
  maintenance_equipment_meter/static/description/index.html
  maintenance_equipment_meter/tests/__init__.py
  maintenance_equipment_meter/tests/test_equipment_meter.py
  maintenance_equipment_meter/views/maintenance_equipment.xml
  maintenance_equipment_meter/views/maintenance_equipment_meter.xml
  maintenance_equipment_meter/views/maintenance_request.xml
  setup/maintenance_equipment_meter/odoo/addons/maintenance_equipment_meter
  setup/maintenance_equipment_meter/setup.py
Labels: bot is merging ⏳

#392 [MIG] [16.0] maintenance_plan_activity: migration to 16.0
  maintenance_plan_activity/README.rst
  maintenance_plan_activity/__init__.py
  maintenance_plan_activity/__manifest__.py
  maintenance_plan_activity/i18n/es.po
  maintenance_plan_activity/i18n/it.po
  maintenance_plan_activity/i18n/maintenance_plan_activity.pot
  maintenance_plan_activity/models/__init__.py
  maintenance_plan_activity/models/maintenance.py
  maintenance_plan_activity/models/maintenance_planned_activity.py
  maintenance_plan_activity/readme/CONTRIBUTORS.rst
  maintenance_plan_activity/readme/DESCRIPTION.rst
  maintenance_plan_activity/security/ir.model.access.csv
  maintenance_plan_activity/static/description/icon.png
  maintenance_plan_activity/static/description/index.html
  maintenance_plan_activity/static/description/maintenance_plan_activity.png
  maintenance_plan_activity/tests/__init__.py
  maintenance_plan_activity/tests/test_maintenance_plan_activity.py
  maintenance_plan_activity/views/maintenance_views.xml
  setup/maintenance_plan_activity/odoo/addons/maintenance_plan_activity
  setup/maintenance_plan_activity/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#389 16.0 [MIG] maintenance_location
  maintenance_location/README.rst
  maintenance_location/__init__.py
  maintenance_location/__manifest__.py
  maintenance_location/i18n/es.po
  maintenance_location/i18n/it.po
  maintenance_location/i18n/maintenance_location.pot
  maintenance_location/models/__init__.py
  maintenance_location/models/maintenance_equipment.py
  maintenance_location/models/maintenance_location.py
  maintenance_location/models/maintenance_plan.py
  maintenance_location/models/maintenance_request.py
  maintenance_location/readme/CONTRIBUTORS.rst
  maintenance_location/readme/DESCRIPTION.rst
  maintenance_location/security/ir.model.access.csv
  maintenance_location/static/description/icon.png
  maintenance_location/static/description/index.html
  maintenance_location/tests/__init__.py
  maintenance_location/tests/test_maintenance_location.py
  maintenance_location/views/maintenance_equipment.xml
  maintenance_location/views/maintenance_location.xml
  maintenance_location/views/maintenance_plan.xml
  maintenance_location/views/maintenance_request.xml
  setup/maintenance_location/odoo/addons/maintenance_location
  setup/maintenance_location/setup.py
Labels: bot is merging ⏳

#379 [ADD] maintenance_inspection
  maintenance_inspection/README.rst
  maintenance_inspection/__init__.py
  maintenance_inspection/__manifest__.py
  maintenance_inspection/models/__init__.py
  maintenance_inspection/models/maintenance_equipment.py
  maintenance_inspection/models/maintenance_inspection_item.py
  maintenance_inspection/models/maintenance_inspection_line.py
  maintenance_inspection/models/maintenance_plan.py
  maintenance_inspection/models/maintenance_request.py
  maintenance_inspection/readme/CONTRIBUTORS.rst
  maintenance_inspection/readme/DESCRIPTION.rst
  maintenance_inspection/readme/USAGE.rst
  maintenance_inspection/security/ir.model.access.csv
  maintenance_inspection/static/description/icon.png
  maintenance_inspection/static/description/index.html
  maintenance_inspection/tests/__init__.py
  maintenance_inspection/tests/test_inspection.py
  maintenance_inspection/views/maintenance_inspection_item.xml
  maintenance_inspection/views/maintenance_inspection_line.xml
  maintenance_inspection/views/maintenance_plan.xml
  maintenance_inspection/views/maintenance_request.xml
  setup/maintenance_inspection/odoo/addons/maintenance_inspection
  setup/maintenance_inspection/setup.py
Labels: approved, bot is merging ⏳
