Repository OCA/maintenance, pull requests merged in 2025-01, with the labels that each got.

#441 [17.0][MIG] maintenance_equipment_usage: Migration to 17.0
  maintenance_equipment_usage/README.rst
  maintenance_equipment_usage/__init__.py
  maintenance_equipment_usage/__manifest__.py
  maintenance_equipment_usage/data/ir_sequence_data.xml
  maintenance_equipment_usage/i18n/es.po
  maintenance_equipment_usage/i18n/it.po
  maintenance_equipment_usage/i18n/maintenance_equipment_usage.pot
  maintenance_equipment_usage/models/__init__.py
  maintenance_equipment_usage/models/maintenance_equipment.py
  maintenance_equipment_usage/models/maintenance_equipment_usage.py
  maintenance_equipment_usage/pyproject.toml
  maintenance_equipment_usage/readme/CONTRIBUTORS.md
  maintenance_equipment_usage/readme/DESCRIPTION.md
  maintenance_equipment_usage/security/ir.model.access.csv
  maintenance_equipment_usage/security/security.xml
  maintenance_equipment_usage/static/description/icon.png
  maintenance_equipment_usage/static/description/index.html
  maintenance_equipment_usage/tests/__init__.py
  maintenance_equipment_usage/tests/test_maintenance_equipment_usage.py
  maintenance_equipment_usage/views/maintenance_equipment_usage_views.xml
  maintenance_equipment_usage/views/maintenance_equipment_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#425 [17.0][FIX] maintenance_timesheet: lost files in directory report
  maintenance_timesheet/__init__.py
  maintenance_timesheet/report/__init__.py
  maintenance_timesheet/report/timesheets_analysis_report.py
Labels: approved, ready to merge, bot is merging ⏳

#444 [17.0][IMP] base_maintenance: Fine-tuning of the form view
  base_maintenance/views/maintenance_request_views.xml
  maintenance_plan/views/maintenance_equipment_views.xml
Labels: bot is merging ⏳

#437 [17.0][FIX] maintenance_plan: fix the use of id in act_window
  maintenance_plan/views/maintenance_plan_views.xml
Labels: bot is merging ⏳

#443 [17.0][MIG] maintenance_request_employee: Migration to version 17.0
  maintenance_request_employee/README.rst
  maintenance_request_employee/__init__.py
  maintenance_request_employee/__manifest__.py
  maintenance_request_employee/i18n/es.po
  maintenance_request_employee/i18n/it.po
  maintenance_request_employee/i18n/maintenance_request_employee.pot
  maintenance_request_employee/models/__init__.py
  maintenance_request_employee/models/maintenance_request.py
  maintenance_request_employee/pyproject.toml
  maintenance_request_employee/readme/CONTRIBUTORS.md
  maintenance_request_employee/readme/DESCRIPTION.md
  maintenance_request_employee/static/description/icon.png
  maintenance_request_employee/static/description/icon.svg
  maintenance_request_employee/static/description/index.html
  maintenance_request_employee/views/maintenance_request_views.xml
Labels: approved, bot is merging ⏳
